---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 90
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      extensions:
        - ".js"
        - ".jsx"
  fixme:
    enabled: true
    exclude_fingerprints:
      - 063e105fd06bf7d28c3ae977517b81af
ratings:
  paths:
  - "src/**/*.css"
  - "src/**/*.js"
  - "src/**/*.jsx"
  - "lib/**/*.js"
  - "bin/**/*.js"
exclude_paths:
- node_modules/
- coverage/
- .nyc_output/
- mochawesome-report/
- docs/
- dist/
- test/
- webpack/
- bin/*.js
- lib/*.js
