version: '2'
checks:
  method-lines:
    config:
      threshold: 75
  similar-code:
    config:
      threshold: 90
exclude_patterns:
  - 'bin/*.js'
  - 'dist/'
  - 'docs/'
  - 'lib/*.js'
  - 'node_modules/'
  - 'test-functional/'
  - 'test/'
  - 'webpack.config.js'
  - 'webpack.loaders.js'
